require:
  - rubocop-rspec
  - rubocop-rails
  - rubocop-performance
  - rubocop-md

AllCops:
  TargetRubyVersion: 2.5

# NameLess Chamber

Layout/LineLength:
  Max: 120

Layout/IndentationWidth:
  Width: 2

Layout/DotPosition:
  Enabled: true
  EnforcedStyle: leading

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space
  SupportedStyles:
    - space
    - no_space
    - compact

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
