# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 239c3858410fced167d9fd5c9a7415839cb1de2fc786f7922447e6b291b74b4c73e9ead7a6964c7e6d2477a0cf0237c5d8dcbe749d9739a6d298589a024de33e

test:
  secret_key_base: 04a25778ce87a8c6062d2ee73db68ada13521328fe5915b47e30e2d941a3cd8e20d4d8c9c9553d7da237d636b9f9bd10436bddff36ce43a7e03ab77ae708c083

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
